name: album_app
description: A Flutter application for displaying albums and photos
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_bloc: ^9.1.1  # Updated
  go_router: ^15.1.2    # Updated
  cached_network_image: ^3.3.1
  flutter_lints: ^5.0.0  # Updated

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1  # Updated
